/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/webhooks/{organizationId}/{source}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["receive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/{organizationId}/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["switchOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/workflows/callbacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["callback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{id}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["assign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["demo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/executions/{id}/steps/{actionId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryStep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/executions/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/executions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["timeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/executions/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WebhookResponse: {
            /** Format: uuid */
            incidentId?: string;
            /** @enum {string} */
            status?: "DETECTED" | "TRIAGED" | "INVESTIGATING" | "AWAITING_APPROVAL" | "MITIGATING" | "MONITORING" | "RESOLVED" | "CLOSED" | "CANCELLED";
            /** Format: int32 */
            signalCount?: number;
        };
        CreateOrganizationRequest: {
            name: string;
            slug?: string;
            demoMode?: boolean;
        };
        OrganizationResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            demoMode?: boolean;
        };
        SwitchOrganizationResponse: {
            accessToken?: string;
            /** Format: uuid */
            organizationId?: string;
        };
        TransitionRequest: {
            /** @enum {string} */
            status?: "DETECTED" | "TRIAGED" | "INVESTIGATING" | "AWAITING_APPROVAL" | "MITIGATING" | "MONITORING" | "RESOLVED" | "CLOSED" | "CANCELLED";
        };
        IncidentView: {
            /** Format: uuid */
            id?: string;
            title?: string;
            summary?: string;
            /** @enum {string} */
            status?: "DETECTED" | "TRIAGED" | "INVESTIGATING" | "AWAITING_APPROVAL" | "MITIGATING" | "MONITORING" | "RESOLVED" | "CLOSED" | "CANCELLED";
            /** @enum {string} */
            severity?: "SEV1" | "SEV2" | "SEV3" | "SEV4";
            /** Format: int32 */
            priority?: number;
            affectedService?: string;
            /** Format: uuid */
            assigneeUserId?: string;
            /** Format: int32 */
            signalCount?: number;
            /** Format: date-time */
            firstDetectedAt?: string;
            /** Format: date-time */
            lastSignalAt?: string;
        };
        CommentRequest: {
            body: string;
        };
        CommentView: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            authorUserId?: string;
            body?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        AssignRequest: {
            /** Format: uuid */
            assigneeUserId?: string;
        };
        CreateExecutionRequest: {
            /** Format: uuid */
            incidentId?: string;
            workflowKey: string;
        };
        ExecutionView: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            incidentId?: string;
            workflowKey?: string;
            /** Format: int32 */
            workflowVersion?: number;
            /** @enum {string} */
            status?: "QUEUED" | "RUNNING" | "PAUSED_FOR_APPROVAL" | "SUCCEEDED" | "PARTIALLY_SUCCEEDED" | "FAILED" | "TIMED_OUT" | "CANCELLED";
            allowedActionIds?: string[];
            /** Format: date-time */
            timeoutAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        StepView: {
            /** Format: uuid */
            id?: string;
            actionId?: string;
            name?: string;
            /** Format: int32 */
            sequence?: number;
            /** @enum {string} */
            status?: "QUEUED" | "RUNNING" | "WAITING" | "APPROVED" | "DENIED" | "SUCCEEDED" | "FAILED" | "SKIPPED";
            /** Format: int32 */
            attempt?: number;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string;
            errorCode?: string;
            errorMessage?: string;
            output?: {
                [key: string]: unknown;
            };
        };
        SignupRequest: {
            email: string;
            password?: string;
            displayName: string;
        };
        AuthResponse: {
            accessToken?: string;
            /** Format: int64 */
            expiresIn?: number;
            user?: components["schemas"]["UserView"];
        };
        UserView: {
            /** Format: uuid */
            id?: string;
            email?: string;
            displayName?: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        IncidentPage: {
            items?: components["schemas"]["IncidentView"][];
            nextCursor?: string;
            hasMore?: boolean;
        };
        EvidenceView: {
            /** Format: uuid */
            id?: string;
            kind?: string;
            title?: string;
            content?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            collectedAt?: string;
        };
        IncidentDetail: {
            incident?: components["schemas"]["IncidentView"];
            evidence?: components["schemas"]["EvidenceView"][];
            comments?: components["schemas"]["CommentView"][];
        };
        ComponentHealth: {
            status?: string;
            message?: string;
            error?: string;
        };
        HealthResponse: {
            status?: string;
            timestamp?: string;
            uptime?: string;
            components?: {
                [key: string]: components["schemas"]["ComponentHealth"];
            };
        };
        EventView: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            stepExecutionId?: string;
            type?: string;
            status?: string;
            message?: string;
            details?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            occurredAt?: string;
        };
        ExecutionTimeline: {
            execution?: components["schemas"]["ExecutionView"];
            steps?: components["schemas"]["StepView"][];
            events?: components["schemas"]["EventView"][];
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        CurrentUserResponse: {
            /** Format: uuid */
            id?: string;
            email?: string;
            displayName?: string;
            /** Format: uuid */
            selectedOrganizationId?: string;
            organizations?: components["schemas"]["OrganizationMembershipResponse"][];
        };
        OrganizationMembershipResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            demoMode?: boolean;
            role?: string;
        };
        ErrorResponse: {
            code?: string;
            message?: string;
            /** Format: int32 */
            status?: number;
            correlationId?: string;
            validationErrors?: {
                field?: string;
                message?: string;
                rejectedValue?: Record<string, never>;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    receive: {
        parameters: {
            query?: never;
            header: {
                "X-Delivery-ID": string;
                "X-Webhook-Nonce": string;
                "X-Webhook-Timestamp": string;
                "X-Webhook-Signature"?: string;
                "X-Hub-Signature-256"?: string;
            };
            path: {
                organizationId: string;
                source: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WebhookResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizationResponse"];
                };
            };
        };
    };
    switchOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SwitchOrganizationResponse"];
                };
            };
        };
    };
    callback: {
        parameters: {
            query?: never;
            header: {
                "X-Execution-Token": string;
                "X-Internal-Timestamp": string;
                "X-Internal-Nonce": string;
                "X-Internal-Signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    transition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IncidentView"];
                };
            };
        };
    };
    comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommentView"];
                };
            };
        };
    };
    assign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IncidentView"];
                };
            };
        };
    };
    demo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IncidentView"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExecutionRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExecutionView"];
                };
            };
        };
    };
    retryStep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                actionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StepView"];
                };
            };
        };
    };
    retry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExecutionView"];
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                status?: "DETECTED" | "TRIAGED" | "INVESTIGATING" | "AWAITING_APPROVAL" | "MITIGATING" | "MONITORING" | "RESOLVED" | "CLOSED" | "CANCELLED";
                severity?: "SEV1" | "SEV2" | "SEV3" | "SEV4";
                serviceName?: string;
                q?: string;
                cursor?: string;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IncidentPage"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IncidentDetail"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    timeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExecutionTimeline"];
                };
            };
        };
    };
    events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    current: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
}
